// ========================================
// ALL NON-HINDU RELIGIONS ENHANCED
// Comprehensive Religion-Specific Data
// ========================================
// 
// This file contains all data structures for:
// 1. Christian Pilgrims
// 2. Muslim Travelers
// 3. Buddhist Followers
// 4. Jain Pilgrims
// 5. Jewish Heritage
// 6. Bahá'í Visitors
// 7. Indigenous & Tribal
// 8. Parsi Heritage
//
// Each religion has:
// - Sacred sites
// - Rituals & practices
// - Festivals calendar
// - Sacred text quotes
// - Pilgrimage packages
// ========================================

export const religionData = {
  // ========================================
  // ✝️ CHRISTIAN PILGRIMS
  // ========================================
  christian: {
    name: 'Christian Pilgrims',
    emoji: '✝️',
    subtitle: 'Sacred Churches & Holy Basilicas',
    gradient: 'from-blue-500 to-indigo-600',
    sacredText: {
      name: 'Bible',
      quote: '"For God so loved the world that he gave his one and only Son..."',
      translation: 'John 3:16',
      source: 'Holy Bible - New Testament',
    },
    sites: [
      {
        id: 'christian-site-1',
        name: '[Admin: St. Thomas Basilica]',
        location: '[Admin: Chennai], [Admin: Tamil Nadu]',
        subtitle: 'Tomb of St. Thomas the Apostle',
        description: 'Sacred site where St. Thomas, one of the twelve apostles, was martyred',
        badge: 'MOST SACRED',
        deity: 'St. Thomas the Apostle',
        significance: 'APOSTOLIC HERITAGE',
        visitors: '50,000+ annually',
        accessibility: 'Fully Accessible',
        gradient: 'from-blue-500 to-indigo-600',
      },
      {
        id: 'christian-site-2',
        name: '[Admin: Velankanni Church]',
        location: '[Admin: Velankanni], [Admin: Tamil Nadu]',
        subtitle: 'Our Lady of Good Health',
        description: 'Major pilgrimage center for devotees of Mother Mary',
        badge: 'MIRACULOUS SHRINE',
        deity: 'Our Lady of Good Health',
        significance: 'HEALING & MIRACLES',
        visitors: '2 million+ annually',
        accessibility: 'Senior-Friendly',
        gradient: 'from-cyan-500 to-blue-600',
      },
      {
        id: 'christian-site-3',
        name: '[Admin: Basilica of Bom Jesus]',
        location: '[Admin: Old Goa], [Admin: Goa]',
        subtitle: 'Remains of St. Francis Xavier',
        description: 'UNESCO World Heritage Site holding the mortal remains of St. Francis Xavier',
        badge: 'UNESCO HERITAGE',
        deity: 'St. Francis Xavier',
        significance: 'JESUIT LEGACY',
        visitors: '1 million+ annually',
        accessibility: 'Wheelchair Access',
        gradient: 'from-amber-500 to-orange-600',
      },
      {
        id: 'christian-site-4',
        name: '[Admin: San Thome Cathedral]',
        location: '[Admin: Mylapore Chennai], [Admin: Tamil Nadu]',
        subtitle: 'Built over St. Thomas tomb',
        description: 'One of only three churches in the world built over apostles tombs',
        badge: 'APOSTOLIC TOMB',
        deity: 'St. Thomas',
        significance: 'ANCIENT HERITAGE',
        visitors: '100,000+ annually',
        accessibility: 'Fully Accessible',
        gradient: 'from-red-500 to-rose-600',
      },
    ],
    rituals: [
      {
        id: 'christian-ritual-1',
        name: 'Holy Mass',
        description: 'Eucharistic celebration and worship service',
        duration: '1 hour',
        site: '[Admin: All Churches]',
        procedure: 'Liturgy of the Word followed by Liturgy of the Eucharist',
        significance: 'Central act of Christian worship',
        participants: 'Open to all',
        icon: '✝️',
      },
      {
        id: 'christian-ritual-2',
        name: 'Novena',
        description: 'Nine days of prayer for special intentions',
        duration: '9 days',
        site: '[Admin: Velankanni & Major Shrines]',
        procedure: 'Daily prayers, rosary, and special petitions',
        significance: 'Seeking intercession of Mary and Saints',
        participants: 'Devotees worldwide',
        icon: '📿',
      },
      {
        id: 'christian-ritual-3',
        name: 'Way of the Cross',
        description: 'Meditation on Christ\'s journey to Calvary',
        duration: '30-45 minutes',
        site: '[Admin: Churches with Stations]',
        procedure: 'Walking meditation through 14 stations',
        significance: 'Passion of Christ remembrance',
        participants: 'Individual or groups',
        icon: '🙏',
      },
      {
        id: 'christian-ritual-4',
        name: 'Veneration of Relics',
        description: 'Honoring remains of St. Francis Xavier',
        duration: '15-30 minutes',
        site: '[Admin: Bom Jesus Basilica]',
        procedure: 'Prayer before the crystal casket',
        significance: 'Connection to apostolic mission',
        participants: 'Pilgrims',
        icon: '⛪',
      },
    ],
    festivals: [
      {
        id: 'christian-festival-1',
        name: 'Christmas',
        date: '[Admin: December 25]',
        dateRange: 'December 25',
        description: 'Birth of Jesus Christ',
        significance: 'MOST IMPORTANT FEAST',
        celebrations: 'Midnight Mass, nativity scenes, carol singing',
        venue: '[Admin: All Churches]',
        expectedVisitors: '2 million+ nationwide',
        rituals: ['Midnight Mass', 'Crib blessing', 'Carol services'],
        icon: '🎄',
        color: 'from-green-500 to-red-600',
      },
      {
        id: 'christian-festival-2',
        name: 'Easter',
        date: '[Admin: March/April (varies)]',
        dateRange: 'Movable feast (Spring)',
        description: 'Resurrection of Jesus Christ',
        significance: 'HOLIEST DAY',
        celebrations: 'Easter Vigil, sunrise services, blessing of food',
        venue: '[Admin: All Churches]',
        expectedVisitors: '3 million+ nationwide',
        rituals: ['Easter Vigil', 'Sunrise service', 'Alleluia'],
        icon: '🐣',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'christian-festival-3',
        name: 'Good Friday',
        date: '[Admin: Friday before Easter]',
        dateRange: 'Movable (Spring)',
        description: 'Crucifixion of Jesus Christ',
        significance: 'PASSION REMEMBRANCE',
        celebrations: 'Stations of the Cross, Passion reading, fasting',
        venue: '[Admin: All Churches]',
        expectedVisitors: '2 million+',
        rituals: ['Veneration of Cross', 'Passion reading', 'Silent prayer'],
        icon: '✝️',
        color: 'from-purple-600 to-indigo-700',
      },
      {
        id: 'christian-festival-4',
        name: 'Feast of Our Lady of Velankanni',
        date: '[Admin: September 8]',
        dateRange: 'September 8',
        description: 'Nativity of Mary - Velankanni Festival',
        significance: 'MARIAN DEVOTION',
        celebrations: 'Novena, procession, flag hoisting',
        venue: '[Admin: Velankanni]',
        expectedVisitors: '500,000+ over 10 days',
        rituals: ['Novena', 'Candle offering', 'Procession'],
        icon: '🕯️',
        color: 'from-blue-400 to-cyan-500',
      },
      {
        id: 'christian-festival-5',
        name: 'Feast of St. Thomas',
        date: '[Admin: July 3]',
        dateRange: 'July 3',
        description: 'Commemoration of St. Thomas the Apostle',
        significance: 'APOSTOLIC LEGACY',
        celebrations: 'Special Mass, procession, cultural programs',
        venue: '[Admin: Mylapore Chennai]',
        expectedVisitors: '100,000+',
        rituals: ['Solemn Mass', 'Procession', 'Blessing'],
        icon: '🕊️',
        color: 'from-indigo-500 to-purple-600',
      },
    ],
    packages: [
      {
        id: 'christian-package-1',
        name: '[Admin: South India Christian Heritage]',
        duration: '10 days',
        price: '₹75,000',
        description: 'Visit major Christian pilgrimage sites across South India',
        inclusions: [
          'AC transport with experienced driver',
          'Comfortable hotel accommodation',
          'Daily breakfast and dinner',
          'Mass arrangements at sacred sites',
          'Senior care assistance',
          'Wheelchair accessibility',
          'Guided church tours',
        ],
        highlights: [
          'Velankanni Basilica darshan',
          'St. Thomas tomb visit',
          'Bom Jesus Basilica Goa',
          'Attend Sunday Mass',
        ],
        dates: '[Admin: Sep-Dec preferred]',
        groupSize: '8-15 people',
        badge: 'HERITAGE CIRCUIT',
        gradient: 'from-blue-500 to-indigo-600',
      },
      {
        id: 'christian-package-2',
        name: '[Admin: Christmas Special Package]',
        duration: '7 days',
        price: '₹55,000',
        description: 'Experience Christmas celebrations at sacred churches',
        inclusions: [
          'Midnight Mass tickets',
          'Christmas feast meals',
          'Carol singing participation',
          'Nativity scene tours',
          'Comfortable accommodation',
          'Senior-friendly transport',
        ],
        highlights: [
          'Midnight Mass at major basilicas',
          'Christmas carol evenings',
          'Nativity celebrations',
          'New Year blessings',
        ],
        dates: '[Admin: Dec 20-27]',
        groupSize: '10-20 people',
        badge: 'FESTIVAL SPECIAL',
        gradient: 'from-green-500 to-red-600',
      },
      {
        id: 'christian-package-3',
        name: '[Admin: Easter Pilgrimage]',
        duration: '6 days',
        price: '₹50,000',
        description: 'Holy Week & Easter celebrations',
        inclusions: [
          'Good Friday services',
          'Easter Vigil participation',
          'Way of the Cross meditation',
          'Breakfast and dinner',
          'AC transport',
          'Prayer book included',
        ],
        highlights: [
          'Good Friday Passion',
          'Easter Vigil ceremony',
          'Sunrise service',
          'Blessing of food',
        ],
        dates: '[Admin: Holy Week (Mar/Apr)]',
        groupSize: '6-12 people',
        badge: 'EASTER SPECIAL',
        gradient: 'from-purple-500 to-pink-600',
      },
    ],
  },

  // ========================================
  // ☪️ MUSLIM TRAVELERS
  // ========================================
  muslim: {
    name: 'Muslim Travelers',
    emoji: '☪️',
    subtitle: 'Sacred Dargahs & Heritage Mosques',
    gradient: 'from-green-500 to-emerald-600',
    sacredText: {
      name: 'Quran',
      quote: '"Indeed, the first House [of worship] established for mankind was that at Makkah..."',
      translation: 'Surah Al-Imran (3:96)',
      source: 'Holy Quran',
    },
    sites: [
      {
        id: 'muslim-site-1',
        name: '[Admin: Ajmer Sharif Dargah]',
        location: '[Admin: Ajmer], [Admin: Rajasthan]',
        subtitle: 'Shrine of Moinuddin Chishti',
        description: 'Tomb of Sufi saint Khwaja Moinuddin Chishti',
        badge: 'MOST SACRED',
        deity: 'Khwaja Moinuddin Chishti',
        significance: 'SUFI SPIRITUALITY',
        visitors: '150,000 daily during Urs',
        accessibility: 'Fully Accessible',
        gradient: 'from-green-500 to-emerald-600',
      },
      {
        id: 'muslim-site-2',
        name: '[Admin: Haji Ali Dargah]',
        location: '[Admin: Mumbai], [Admin: Maharashtra]',
        subtitle: 'Mosque and Dargah on Islet',
        description: 'Tomb of Muslim merchant Haji Ali, accessed via causeway',
        badge: 'ICONIC SHRINE',
        deity: 'Pir Haji Ali Shah Bukhari',
        significance: 'SPIRITUAL RETREAT',
        visitors: '40,000 weekly',
        accessibility: 'Tidal Access (check timings)',
        gradient: 'from-teal-500 to-cyan-600',
      },
      {
        id: 'muslim-site-3',
        name: '[Admin: Mecca Masjid]',
        location: '[Admin: Hyderabad], [Admin: Telangana]',
        subtitle: 'One of India\'s largest mosques',
        description: 'Historic mosque with bricks from Mecca',
        badge: 'HERITAGE MOSQUE',
        deity: 'Islamic Worship',
        significance: 'MUGHAL ARCHITECTURE',
        visitors: '10,000+ on Fridays',
        accessibility: 'Fully Accessible',
        gradient: 'from-blue-500 to-indigo-600',
      },
      {
        id: 'muslim-site-4',
        name: '[Admin: Nizamuddin Dargah]',
        location: '[Admin: Delhi], [Admin: NCR]',
        subtitle: 'Shrine of Nizamuddin Auliya',
        description: 'Sufi saint\'s dargah, center of Qawwali traditions',
        badge: 'SUFI CENTER',
        deity: 'Nizamuddin Auliya',
        significance: 'QAWWALI TRADITION',
        visitors: '50,000+ weekly',
        accessibility: 'Senior-Friendly',
        gradient: 'from-amber-500 to-orange-600',
      },
    ],
    rituals: [
      {
        id: 'muslim-ritual-1',
        name: 'Urs Celebration',
        description: 'Annual death anniversary of Sufi saints',
        duration: '3-6 days',
        site: '[Admin: Ajmer Sharif & Other Dargahs]',
        procedure: 'Qawwali, prayers, offerings, and communal meals',
        significance: 'Honoring Sufi saints',
        participants: '100,000+ pilgrims',
        icon: '🕌',
      },
      {
        id: 'muslim-ritual-2',
        name: 'Qawwali',
        description: 'Devotional Sufi music and poetry',
        duration: '1-3 hours',
        site: '[Admin: Nizamuddin & Ajmer]',
        procedure: 'Live musical performance of Sufi kalam',
        significance: 'Spiritual ecstasy through music',
        participants: 'Open to all',
        icon: '🎶',
      },
      {
        id: 'muslim-ritual-3',
        name: 'Zikr (Dhikr)',
        description: 'Remembrance of Allah through chanting',
        duration: '30 minutes - 1 hour',
        site: '[Admin: Khanqahs & Dargahs]',
        procedure: 'Repetitive chanting of Allah\'s names',
        significance: 'Purification of heart',
        participants: 'Sufi circles',
        icon: '📿',
      },
      {
        id: 'muslim-ritual-4',
        name: 'Chadar Offering',
        description: 'Cloth offering at saint\'s tomb',
        duration: '15-30 minutes',
        site: '[Admin: Dargahs]',
        procedure: 'Placing embroidered cloth on mazar with prayers',
        significance: 'Seeking blessings and barkat',
        participants: 'Devotees',
        icon: '🧵',
      },
    ],
    festivals: [
      {
        id: 'muslim-festival-1',
        name: 'Urs of Khwaja Moinuddin Chishti',
        date: '[Admin: Rajab 1-6 (Islamic Calendar)]',
        dateRange: 'Rajab (7th Islamic month)',
        description: 'Annual Urs at Ajmer Sharif Dargah',
        significance: 'LARGEST URS IN INDIA',
        celebrations: 'Qawwali, langar, prayers, special ceremonies',
        venue: '[Admin: Ajmer Sharif]',
        expectedVisitors: '500,000+ over 6 days',
        rituals: ['Qawwali nights', 'Chadar offering', 'Fateha'],
        icon: '🌙',
        color: 'from-green-400 to-emerald-600',
      },
      {
        id: 'muslim-festival-2',
        name: 'Eid-ul-Fitr',
        date: '[Admin: 1 Shawwal (After Ramadan)]',
        dateRange: 'Shawwal 1 (Islamic calendar)',
        description: 'Festival marking end of Ramadan fasting',
        significance: 'CELEBRATION OF FASTING',
        celebrations: 'Eid prayers, charity, feasts, family gatherings',
        venue: '[Admin: All Mosques & Eidgahs]',
        expectedVisitors: 'Millions nationwide',
        rituals: ['Eid Salah', 'Zakat al-Fitr', 'Takbir'],
        icon: '🌙',
        color: 'from-teal-400 to-cyan-500',
      },
      {
        id: 'muslim-festival-3',
        name: 'Eid-ul-Adha',
        date: '[Admin: 10 Dhul Hijjah]',
        dateRange: 'Dhul Hijjah 10',
        description: 'Festival of Sacrifice commemorating Ibrahim',
        significance: 'SACRIFICE & DEVOTION',
        celebrations: 'Qurbani (sacrifice), prayers, charity distribution',
        venue: '[Admin: All Mosques]',
        expectedVisitors: 'Millions nationwide',
        rituals: ['Eid Salah', 'Qurbani', 'Distribution to poor'],
        icon: '🐑',
        color: 'from-green-500 to-lime-600',
      },
      {
        id: 'muslim-festival-4',
        name: 'Shab-e-Barat',
        date: '[Admin: 15 Shaban]',
        dateRange: 'Mid-Shaban (8th month)',
        description: 'Night of forgiveness and blessings',
        significance: 'NIGHT OF RECORDS',
        celebrations: 'Night prayers, Quran recitation, charity',
        venue: '[Admin: Mosques & Homes]',
        expectedVisitors: 'Community-wide',
        rituals: ['Night vigil', 'Dua', 'Grave visits'],
        icon: '🌟',
        color: 'from-blue-500 to-indigo-600',
      },
    ],
    packages: [
      {
        id: 'muslim-package-1',
        name: '[Admin: Sufi Dargah Circuit]',
        duration: '12 days',
        price: '₹85,000',
        description: 'Visit major Sufi shrines across India',
        inclusions: [
          'AC transport',
          'Halal meals throughout',
          'Accommodation near dargahs',
          'Prayer time arrangements',
          'Qawwali session access',
          'Senior care support',
          'Wheelchair availability',
        ],
        highlights: [
          'Ajmer Sharif Urs experience',
          'Nizamuddin Qawwali nights',
          'Haji Ali pilgrimage',
          'Sufi heritage exploration',
        ],
        dates: '[Admin: Rajab preferred (Urs season)]',
        groupSize: '8-15 people',
        badge: 'SUFI HERITAGE',
        gradient: 'from-green-500 to-emerald-600',
      },
      {
        id: 'muslim-package-2',
        name: '[Admin: Urs Special Package]',
        duration: '7 days',
        price: '₹60,000',
        description: 'Experience Ajmer Sharif Urs festival',
        inclusions: [
          'Urs ceremony access',
          'Qawwali session tickets',
          'Halal food included',
          'Comfortable lodging',
          'Prayer facilities',
          'Guided dargah tours',
        ],
        highlights: [
          'Main Urs ceremonies',
          'Famous Qawwali performances',
          'Chadar offering',
          'Langar participation',
        ],
        dates: '[Admin: Rajab 1-6]',
        groupSize: '10-20 people',
        badge: 'FESTIVAL SPECIAL',
        gradient: 'from-amber-500 to-orange-600',
      },
      {
        id: 'muslim-package-3',
        name: '[Admin: Heritage Mosques Tour]',
        duration: '9 days',
        price: '₹70,000',
        description: 'Explore historic mosques and Islamic architecture',
        inclusions: [
          'Architectural guides',
          'Halal meals',
          'Friday Jummah arrangements',
          'AC transport',
          'Hotel accommodation',
          'Historical documentation',
        ],
        highlights: [
          'Mecca Masjid Hyderabad',
          'Jama Masjid Delhi',
          'Mughal architecture study',
          'Islamic heritage sites',
        ],
        dates: '[Admin: Oct-Mar]',
        groupSize: '6-12 people',
        badge: 'HERITAGE TOUR',
        gradient: 'from-blue-500 to-indigo-600',
      },
    ],
  },

  // ========================================
  // ☸️ BUDDHIST FOLLOWERS
  // ========================================
  buddhist: {
    name: 'Buddhist Followers',
    emoji: '☸️',
    subtitle: 'Buddha\'s Path & Sacred Sites',
    gradient: 'from-orange-500 to-amber-600',
    sacredText: {
      name: 'Tripitaka',
      quote: '"Better than a thousand hollow words, is one word that brings peace..."',
      translation: 'Dhammapada 100',
      source: 'Tripitaka - Sutta Pitaka',
    },
    sites: [
      {
        id: 'buddhist-site-1',
        name: '[Admin: Sarnath]',
        location: '[Admin: Varanasi], [Admin: Uttar Pradesh]',
        subtitle: 'Where Buddha gave first sermon',
        description: 'Sacred site of Buddha\'s first teaching of Dharma',
        badge: 'MOST SACRED',
        deity: 'Gautama Buddha',
        significance: 'FIRST SERMON (DHAMMACAKKAPPAVATTANA)',
        visitors: '100,000+ annually',
        accessibility: 'Fully Accessible',
        gradient: 'from-orange-500 to-amber-600',
      },
      {
        id: 'buddhist-site-2',
        name: '[Admin: Bodh Gaya]',
        location: '[Admin: Gaya], [Admin: Bihar]',
        subtitle: 'Site of Buddha\'s enlightenment',
        description: 'Mahabodhi Temple where Buddha attained enlightenment',
        badge: 'ENLIGHTENMENT SITE',
        deity: 'Gautama Buddha',
        significance: 'BODHI TREE & ENLIGHTENMENT',
        visitors: '500,000+ annually',
        accessibility: 'Senior-Friendly',
        gradient: 'from-green-500 to-emerald-600',
      },
      {
        id: 'buddhist-site-3',
        name: '[Admin: Rumtek Monastery]',
        location: '[Admin: Gangtok], [Admin: Sikkim]',
        subtitle: 'Seat of Karmapa',
        description: 'Tibetan Buddhist monastery, center of Kagyu lineage',
        badge: 'TIBETAN CENTER',
        deity: 'Karmapa',
        significance: 'TIBETAN BUDDHISM HQ',
        visitors: '50,000+ annually',
        accessibility: 'Mountain Access',
        gradient: 'from-red-500 to-pink-600',
      },
      {
        id: 'buddhist-site-4',
        name: '[Admin: Sanchi Stupa]',
        location: '[Admin: Sanchi], [Admin: Madhya Pradesh]',
        subtitle: 'Ancient Buddhist complex',
        description: 'UNESCO site with Great Stupa commissioned by Emperor Ashoka',
        badge: 'UNESCO HERITAGE',
        deity: 'Buddhist Relics',
        significance: 'ASHOKAN LEGACY',
        visitors: '80,000+ annually',
        accessibility: 'Fully Accessible',
        gradient: 'from-blue-500 to-indigo-600',
      },
    ],
    rituals: [
      {
        id: 'buddhist-ritual-1',
        name: 'Dharma Reading',
        description: 'Recitation of Buddhist scriptures',
        duration: '1-2 hours',
        site: '[Admin: All Monasteries]',
        procedure: 'Monks chant sutras from Tripitaka',
        significance: 'Spreading Buddha\'s teachings',
        participants: 'Monks and lay followers',
        icon: '📖',
      },
      {
        id: 'buddhist-ritual-2',
        name: 'Meditation (Vipassana)',
        description: 'Mindfulness and insight meditation',
        duration: '30 minutes - full day',
        site: '[Admin: Meditation Centers]',
        procedure: 'Silent sitting, breath awareness, body scanning',
        significance: 'Path to enlightenment',
        participants: 'Individual practitioners',
        icon: '🧘',
      },
      {
        id: 'buddhist-ritual-3',
        name: 'Cham Dance',
        description: 'Sacred masked dance in Tibetan tradition',
        duration: '2-4 hours',
        site: '[Admin: Rumtek & Tibetan Monasteries]',
        procedure: 'Monks perform ritual dance in elaborate costumes',
        significance: 'Driving away evil spirits',
        participants: 'Monastery community',
        icon: '🎭',
      },
      {
        id: 'buddhist-ritual-4',
        name: 'Pradakshina (Circumambulation)',
        description: 'Walking clockwise around sacred sites',
        duration: '15-30 minutes',
        site: '[Admin: Stupas & Temples]',
        procedure: 'Reverent walking meditation around stupa',
        significance: 'Merit accumulation',
        participants: 'All pilgrims',
        icon: '🚶',
      },
    ],
    festivals: [
      {
        id: 'buddhist-festival-1',
        name: 'Buddha Purnima (Vesak)',
        date: '[Admin: Vaishakha Purnima - April/May]',
        dateRange: 'Full moon of Vaishakha',
        description: 'Birth, enlightenment, and Parinirvana of Buddha',
        significance: 'MOST IMPORTANT FESTIVAL',
        celebrations: 'Prayer, meditation, lantern lighting, Dharma talks',
        venue: '[Admin: All Buddhist Sites]',
        expectedVisitors: '500,000+ at Bodh Gaya',
        rituals: ['Bathing Buddha statue', 'Candle procession', 'Dana'],
        icon: '🌕',
        color: 'from-yellow-400 to-orange-500',
      },
      {
        id: 'buddhist-festival-2',
        name: 'Losar (Tibetan New Year)',
        date: '[Admin: February/March]',
        dateRange: 'Tibetan lunar calendar',
        description: 'Tibetan Buddhist New Year celebration',
        significance: 'NEW BEGINNINGS',
        celebrations: 'Cham dance, prayer flags, monastery rituals',
        venue: '[Admin: Tibetan Monasteries]',
        expectedVisitors: '50,000+ in Dharamshala/Sikkim',
        rituals: ['Cham dance', 'Prayer flags', 'Torma offerings'],
        icon: '🎊',
        color: 'from-red-400 to-pink-500',
      },
      {
        id: 'buddhist-festival-3',
        name: 'Asalha Puja (Dharma Day)',
        date: '[Admin: Ashadha Purnima - July]',
        dateRange: 'Full moon of Ashadha',
        description: 'Buddha\'s first sermon at Sarnath',
        significance: 'FIRST TEACHING',
        celebrations: 'Dharma talks, meditation, candlelit processions',
        venue: '[Admin: Sarnath]',
        expectedVisitors: '100,000+',
        rituals: ['Dharma reading', 'Meditation', 'Offerings'],
        icon: '☸️',
        color: 'from-orange-400 to-amber-500',
      },
      {
        id: 'buddhist-festival-4',
        name: 'Magha Puja',
        date: '[Admin: Magha Purnima - February]',
        dateRange: 'Full moon of Magha',
        description: 'Commemoration of Buddha\'s teaching to 1,250 enlightened monks',
        significance: 'SANGHA CELEBRATION',
        celebrations: 'Candle processions, meditation, precept taking',
        venue: '[Admin: Major Monasteries]',
        expectedVisitors: '80,000+',
        rituals: ['Triple circumambulation', 'Candle offering', 'Precepts'],
        icon: '🕯️',
        color: 'from-blue-400 to-indigo-500',
      },
    ],
    packages: [
      {
        id: 'buddhist-package-1',
        name: '[Admin: Buddha\'s Footsteps Circuit]',
        duration: '14 days',
        price: '₹95,000',
        description: 'Complete Buddhist pilgrimage covering all major sites',
        inclusions: [
          'AC transport',
          'Vegetarian meals',
          'Monastery accommodation',
          'Meditation sessions',
          'Dharma talks access',
          'Senior care support',
          'Guided tours',
        ],
        highlights: [
          'Bodh Gaya enlightenment site',
          'Sarnath first sermon',
          'Kushinagar Parinirvana',
          'Lumbini birthplace (Nepal)',
        ],
        dates: '[Admin: Oct-Mar]',
        groupSize: '8-15 people',
        badge: 'COMPLETE CIRCUIT',
        gradient: 'from-orange-500 to-amber-600',
      },
      {
        id: 'buddhist-package-2',
        name: '[Admin: Vesak Special Package]',
        duration: '7 days',
        price: '₹60,000',
        description: 'Buddha Purnima celebrations at sacred sites',
        inclusions: [
          'Vesak ceremony access',
          'Meditation retreat',
          'Vegetarian meals',
          'Comfortable lodging',
          'Prayer accessories',
          'Cultural programs',
        ],
        highlights: [
          'Buddha Purnima at Bodh Gaya',
          'Candle procession',
          'Dharma teachings',
          'Community dana',
        ],
        dates: '[Admin: Vaishakha Purnima]',
        groupSize: '10-20 people',
        badge: 'FESTIVAL SPECIAL',
        gradient: 'from-yellow-500 to-orange-600',
      },
      {
        id: 'buddhist-package-3',
        name: '[Admin: Meditation Retreat Package]',
        duration: '10 days',
        price: '₹55,000',
        description: 'Intensive Vipassana meditation retreat',
        inclusions: [
          'Guided meditation sessions',
          'Simple vegetarian food',
          'Monastery stay',
          'Dharma talks',
          'Silent retreat support',
          'Personal guidance',
        ],
        highlights: [
          'Daily meditation (6+ hours)',
          'Noble silence practice',
          'Dharma discussions',
          'Mindfulness training',
        ],
        dates: '[Admin: Year-round]',
        groupSize: '4-8 people',
        badge: 'RETREAT',
        gradient: 'from-green-500 to-teal-600',
      },
    ],
  },
};
