// ========================================
// REMAINING RELIGIONS ENHANCED DATA
// Jewish, Bahá'í, Parsi, Indigenous
// ========================================

export const remainingEnhancedData = {
  // ========================================
  // ✡ JEWISH HERITAGE
  // ========================================
  jewish: {
    sectionName: 'Shabbat & Heritage',
    sectionSubtitle: 'Synagogue Services & Cultural Heritage',
    sectionIcon: '✡',
    
    sacredTextReference: {
      quote: 'Hear, O Israel: The LORD our God, the LORD is one.',
      translation: 'Shema Yisrael - Deuteronomy 6:4',
      source: 'Torah - Five Books of Moses',
      context: 'Central declaration of Jewish faith, recited daily',
    },

    ritualBookings: [
      {
        id: 'jewish-ritual-1',
        name: 'Synagogue Tour Booking',
        description: 'Guided heritage tour of historic synagogues',
        duration: '1-2 hours',
        price: '[Admin: ₹200 - ₹500 per person]',
        requirements: ['Head covering for men (kippah provided)', 'Modest dress required', 'Photography rules vary'],
        availableTimes: ['Sunday - Thursday: 10:00 AM - 5:00 PM', 'Closed Friday evening & all Saturday'],
        icon: '🕍',
      },
      {
        id: 'jewish-ritual-2',
        name: 'Kosher Meal Request',
        description: 'Pre-order certified kosher meals',
        duration: 'Per meal',
        price: '[Admin: ₹500 - ₹1,500 per meal]',
        requirements: ['24-hour advance notice', 'Vegetarian/Meat options', 'Certification available', 'Limited restaurants in India'],
        availableTimes: ['Lunch: 12:00 PM - 2:00 PM', 'Dinner: 7:00 PM - 9:00 PM'],
        icon: '🍽️',
      },
      {
        id: 'jewish-ritual-3',
        name: 'Shabbat Service Attendance',
        description: 'Join Friday evening or Saturday morning service',
        duration: '2-3 hours',
        price: '[Admin: Free (Community welcome)]',
        requirements: ['Register with community contact', 'No photography on Shabbat', 'Modest dress mandatory'],
        availableTimes: ['Friday: 6:30 PM (sunset)', 'Saturday: 9:00 AM'],
        icon: '🕎',
      },
      {
        id: 'jewish-ritual-4',
        name: 'Heritage Documentation',
        description: 'Access to historical records and archives',
        duration: 'By appointment',
        price: '[Admin: ₹500 research fee]',
        requirements: ['Advance booking (1 week)', 'Scholar/researcher credentials', 'Limited access'],
        availableTimes: ['Monday - Thursday: 2:00 PM - 5:00 PM'],
        icon: '📜',
      },
    ],

    upcomingOccasions: [
      {
        id: 'jewish-occasion-1',
        name: 'Pesach (Passover)',
        date: '[Admin: 15 Nisan - March/April]',
        dateRange: 'Nisan 15-22 (8 days)',
        type: 'festival',
        description: 'Seder meals commemorating Exodus from Egypt',
        bookingRequired: true,
        icon: '🍷',
        color: 'from-blue-400 to-indigo-500',
      },
      {
        id: 'jewish-occasion-2',
        name: 'Rosh Hashanah (New Year)',
        date: '[Admin: 1-2 Tishrei - September/October]',
        dateRange: 'Tishrei 1-2',
        type: 'festival',
        description: 'Jewish New Year with shofar blowing',
        bookingRequired: true,
        icon: '📯',
        color: 'from-amber-400 to-yellow-500',
      },
      {
        id: 'jewish-occasion-3',
        name: 'Yom Kippur (Day of Atonement)',
        date: '[Admin: 10 Tishrei - September/October]',
        dateRange: 'Tishrei 10',
        type: 'special-day',
        description: 'Holiest day - 25-hour fast and prayer',
        bookingRequired: true,
        icon: '🙏',
        color: 'from-purple-500 to-indigo-600',
      },
      {
        id: 'jewish-occasion-4',
        name: 'Hanukkah (Festival of Lights)',
        date: '[Admin: 25 Kislev - November/December]',
        dateRange: 'Kislev 25 - 8 days',
        type: 'festival',
        description: 'Menorah lighting, dreidel games',
        bookingRequired: false,
        icon: '🕎',
        color: 'from-blue-400 to-cyan-500',
      },
    ],

    culturalInsights: [
      {
        id: 'jewish-insight-1',
        title: 'Paradesi Synagogue Strict Rules',
        message: 'Paradesi Synagogue (Kochi) has strict dress codes and is CLOSED on Fridays after 4 PM and all day Saturday (Shabbat). Women: long skirts/pants, covered shoulders. Men: long pants. No photography on Shabbat.',
        type: 'restriction',
        icon: '🚫',
        priority: 'high',
      },
      {
        id: 'jewish-insight-2',
        title: 'Limited Kosher Options',
        message: 'Kosher food availability is extremely limited in India. Only Mumbai and Delhi have certified kosher restaurants. Pre-order meals 24-48 hours in advance. Vegetarian options easier to arrange.',
        type: 'requirement',
        icon: 'ℹ️',
        priority: 'high',
      },
      {
        id: 'jewish-insight-3',
        title: 'Shabbat Travel Restrictions',
        message: 'Observant Jews cannot travel Friday sunset to Saturday sunset (Shabbat). Plan accommodations within walking distance of synagogue. No use of electricity/phones during Shabbat by orthodox visitors.',
        type: 'timing',
        icon: '⏰',
        priority: 'medium',
      },
      {
        id: 'jewish-insight-4',
        title: 'Small Community Size',
        message: 'India\'s Jewish population is now very small (4,000-5,000). Most active communities in Mumbai and Kochi. Advance contact with community leaders recommended for Shabbat/festival participation.',
        type: 'tip',
        icon: '👥',
        priority: 'medium',
      },
    ],
  },

  // ========================================
  // ★ BAHÁ'Í VISITORS
  // ========================================
  bahai: {
    sectionName: 'Silent Reflection',
    sectionSubtitle: 'Prayer Hall & Unity Teachings',
    sectionIcon: '★',
    
    sacredTextReference: {
      quote: 'The earth is but one country, and mankind its citizens.',
      translation: 'Bahá\'u\'lláh',
      source: 'Kitáb-i-Aqdas (Most Holy Book)',
      context: 'Central principle of unity of humanity',
    },

    ritualBookings: [
      {
        id: 'bahai-ritual-1',
        name: 'Prayer Hall Entry',
        description: 'Visit Lotus Temple prayer hall (no ritual, silent only)',
        duration: '15-30 minutes',
        price: '[Admin: Free]',
        requirements: ['STRICT SILENCE mandatory', 'No photography inside hall', 'Sit for minimum 5 minutes', 'No shoes (remove outside)'],
        availableTimes: ['Tuesday - Sunday: 9:00 AM - 7:00 PM', 'Closed Mondays'],
        icon: '🏛️',
      },
      {
        id: 'bahai-ritual-2',
        name: 'Information Center Audio Guide',
        description: 'Multi-lingual guided tour of Bahá\'í teachings',
        duration: '30-45 minutes',
        price: '[Admin: Free]',
        requirements: ['Available in 15+ languages', 'Headphones provided', 'Deposit required (₹100 refundable)'],
        availableTimes: ['9:30 AM - 6:30 PM'],
        icon: '🎧',
      },
      {
        id: 'bahai-ritual-3',
        name: 'Devotional Program',
        description: 'Monthly community devotional gathering',
        duration: '1 hour',
        price: '[Admin: Free (Open to all)]',
        requirements: ['Music and prayers from various faiths', 'No rituals performed', 'Unity in diversity theme'],
        availableTimes: ['Last Sunday of month: 10:00 AM'],
        icon: '🎵',
      },
    ],

    upcomingOccasions: [
      {
        id: 'bahai-occasion-1',
        name: 'Naw-Rúz (Bahá\'í New Year)',
        date: '[Admin: March 21]',
        dateRange: 'March 21 (Spring Equinox)',
        type: 'festival',
        description: 'Bahá\'í New Year celebration',
        bookingRequired: false,
        icon: '🌸',
        color: 'from-pink-400 to-rose-500',
      },
      {
        id: 'bahai-occasion-2',
        name: 'Ridván',
        date: '[Admin: April 21 - May 2]',
        dateRange: '12 days in April-May',
        type: 'festival',
        description: 'Most holy Bahá\'í festival - Declaration of Bahá\'u\'lláh',
        bookingRequired: false,
        icon: '🌟',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'bahai-occasion-3',
        name: 'Birth of Bahá\'u\'lláh',
        date: '[Admin: November 12]',
        dateRange: 'November 12',
        type: 'special-day',
        description: 'Birthday of founder of Bahá\'í Faith',
        bookingRequired: false,
        icon: '🎂',
        color: 'from-blue-400 to-purple-500',
      },
    ],

    culturalInsights: [
      {
        id: 'bahai-insight-1',
        title: 'STRICT SILENCE Rule',
        message: 'Strict silence observed inside Lotus Temple prayer hall. No talking, whispering, or phone use. Children must be supervised. Violators will be asked to leave. This is a place for meditation and prayer.',
        type: 'restriction',
        icon: '🔇',
        priority: 'high',
      },
      {
        id: 'bahai-insight-2',
        title: 'No Photography Inside Prayer Hall',
        message: 'Photography and videography are STRICTLY PROHIBITED inside the prayer hall. Exterior photography is allowed. Security checks at entrance. Mobile phones must be silenced.',
        type: 'restriction',
        icon: '📵',
        priority: 'high',
      },
      {
        id: 'bahai-insight-3',
        title: 'Peak Visiting Hours',
        message: 'Lotus Temple receives 4 million+ visitors annually. Peak hours: 10 AM - 4 PM on weekends. Visit early morning (9-10 AM) or late afternoon (5-6 PM) for shorter queues. Monday closed for maintenance.',
        type: 'timing',
        icon: '⏰',
        priority: 'medium',
      },
      {
        id: 'bahai-insight-4',
        title: 'No Idols or Rituals',
        message: 'Bahá\'í House of Worship has no idols, statues, or religious imagery. No rituals or sermons. Only silent prayer and reflection. Readings from all major religions during devotional programs.',
        type: 'tip',
        icon: 'ℹ️',
        priority: 'medium',
      },
    ],
  },

  // ========================================
  // 🔥 PARSI HERITAGE
  // ========================================
  parsi: {
    sectionName: 'Heritage & Offering',
    sectionSubtitle: 'Zoroastrian Culture & Fire Temple Heritage',
    sectionIcon: '🔥',
    
    sacredTextReference: {
      quote: 'Humata, Hukhta, Hvarshta',
      translation: 'Good Thoughts, Good Words, Good Deeds',
      source: 'Avesta - Yasna',
      context: 'The three pillars of Zoroastrian ethics',
    },

    ritualBookings: [
      {
        id: 'parsi-ritual-1',
        name: 'Sukhad (Sandalwood) Offering',
        description: 'Purchase sandalwood offering for sacred fire',
        duration: 'One-time',
        price: '[Admin: ₹100 - ₹500]',
        requirements: ['Non-Parsis can purchase at entrance', 'Offering placed by priest on your behalf', 'Receipt for donation provided'],
        availableTimes: ['6:00 AM - 9:00 PM (Udvada)'],
        icon: '🌳',
      },
      {
        id: 'parsi-ritual-2',
        name: 'Heritage Walk (Udvada Town)',
        description: 'Guided tour of Parsi heritage sites (museum, town)',
        duration: '2-3 hours',
        price: '[Admin: ₹500 - ₹1,000 per person]',
        requirements: ['Includes Fire Temple exterior, museum, historical homes', 'Sanctum access ONLY for Zoroastrians', 'Photography rules apply'],
        availableTimes: ['9:00 AM, 2:00 PM (Daily tours)'],
        icon: '🚶',
      },
      {
        id: 'parsi-ritual-3',
        name: 'Parsi Cuisine Experience',
        description: 'Traditional Parsi meal at heritage restaurant',
        duration: '1-2 hours',
        price: '[Admin: ₹800 - ₹2,000 per person]',
        requirements: ['Dhansak, Patra ni Machhi, Lagan nu Custard', 'Advance booking recommended', 'Mumbai: Britannia, Jimmy Boy'],
        availableTimes: ['Lunch: 12:00 PM - 3:00 PM'],
        icon: '🍽️',
      },
      {
        id: 'parsi-ritual-4',
        name: 'Museum & Archives Visit',
        description: 'Access to Parsi heritage documentation',
        duration: '1 hour',
        price: '[Admin: ₹200 entry fee]',
        requirements: ['Photography allowed (no flash)', 'Guided tour included', 'Library access by appointment'],
        availableTimes: ['10:00 AM - 5:00 PM (Tue-Sun)'],
        icon: '📚',
      },
    ],

    upcomingOccasions: [
      {
        id: 'parsi-occasion-1',
        name: 'Nowruz (Parsi New Year)',
        date: '[Admin: March 21]',
        dateRange: 'March 21 (Spring Equinox)',
        type: 'festival',
        description: 'Zoroastrian/Parsi New Year - Fire temple prayers',
        bookingRequired: false,
        icon: '🎊',
        color: 'from-orange-400 to-red-500',
      },
      {
        id: 'parsi-occasion-2',
        name: 'Khordad Sal',
        date: '[Admin: August]',
        dateRange: 'Khordad Mah, Khordad Roz',
        type: 'special-day',
        description: 'Birth anniversary of Prophet Zarathushtra',
        bookingRequired: false,
        icon: '🌟',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'parsi-occasion-3',
        name: 'Pateti',
        date: '[Admin: Day before Nowruz]',
        dateRange: 'March 20',
        type: 'special-day',
        description: 'Day of repentance before New Year',
        bookingRequired: false,
        icon: '🙏',
        color: 'from-purple-400 to-indigo-500',
      },
    ],

    culturalInsights: [
      {
        id: 'parsi-insight-1',
        title: 'CRITICAL: Sanctum Access Restricted',
        message: 'Note: Fire Temple sanctum (where sacred fire burns) is accessible ONLY to Zoroastrians. Non-Parsis can visit museum, heritage walk, and exterior. Udvada Atash Behram has 1000+ year old fire.',
        type: 'restriction',
        icon: '🚫',
        priority: 'high',
      },
      {
        id: 'parsi-insight-2',
        title: 'Heritage Over Ritual',
        message: 'Since non-Parsis cannot enter Fire Temple sanctum, focus on heritage aspects: museum, architecture, Parsi Colony walks, cuisine experience. Mumbai has best Parsi restaurants and heritage sites.',
        type: 'tip',
        icon: 'ℹ️',
        priority: 'high',
      },
      {
        id: 'parsi-insight-3',
        title: 'Towers of Silence Restrictions',
        message: 'Towers of Silence (Dakhmas) in Mumbai are STRICTLY OFF-LIMITS to all visitors including Parsis. Only corpse bearers enter. Viewing from distance only. Photography prohibited.',
        type: 'restriction',
        icon: '🚫',
        priority: 'medium',
      },
      {
        id: 'parsi-insight-4',
        title: 'Small Community Support',
        message: 'India\'s Parsi population is declining (60,000). Supporting Parsi heritage through museum visits, cuisine, and heritage tours helps preserve this unique culture. Udvada is the spiritual center.',
        type: 'tip',
        icon: '❤️',
        priority: 'medium',
      },
    ],
  },

  // ========================================
  // 🌿 INDIGENOUS & TRIBAL
  // ========================================
  indigenous: {
    sectionName: 'Nature & Ancestors',
    sectionSubtitle: 'Sacred Traditions & Eco-Cultural Experiences',
    sectionIcon: '🌿',
    
    sacredTextReference: {
      quote: 'The forest is our temple, the river our priest, and nature our sacred text.',
      translation: 'Tribal wisdom passed through generations',
      source: 'Oral Traditions of Indigenous Communities',
      context: 'Reverence for nature as divine',
    },

    ritualBookings: [
      {
        id: 'indigenous-ritual-1',
        name: 'Sacred Grove Guided Walk',
        description: 'Visit protected forest groves with tribal guide',
        duration: '2-3 hours',
        price: '[Admin: ₹500 - ₹1,500 per person]',
        requirements: ['Respectful behavior mandatory', 'No plucking plants/flowers', 'Tribal guide required', 'Photography with permission'],
        availableTimes: ['Morning: 6:00 AM - 9:00 AM', 'Evening: 4:00 PM - 6:00 PM'],
        icon: '🌳',
      },
      {
        id: 'indigenous-ritual-2',
        name: 'Harvest Festival Participation',
        description: 'Join seasonal harvest celebrations (Sarhul, Tusu)',
        duration: 'Half day to full day',
        price: '[Admin: ₹1,000 - ₹3,000 per person]',
        requirements: ['Seasonal availability only', 'Traditional dress appreciated', 'Community meal included', 'Advance booking (1 month)'],
        availableTimes: ['Festival dates (see calendar)'],
        icon: '🌾',
      },
      {
        id: 'indigenous-ritual-3',
        name: 'Tribal Art Workshop',
        description: 'Learn traditional Warli/Gond/Madhubani painting',
        duration: '3-4 hours',
        price: '[Admin: ₹800 - ₹2,500 per person]',
        requirements: ['Materials provided', 'Take home your artwork', 'Support local artisans'],
        availableTimes: ['10:00 AM - 2:00 PM (by appointment)'],
        icon: '🎨',
      },
      {
        id: 'indigenous-ritual-4',
        name: 'Village Homestay Experience',
        description: 'Live with tribal family (1-3 nights)',
        duration: '1-3 nights',
        price: '[Admin: ₹2,000 - ₹4,000 per night]',
        requirements: ['Basic facilities', 'Traditional meals', 'Cultural immersion', 'Book via ethical tourism operators'],
        availableTimes: ['Check-in: 2:00 PM, Check-out: 11:00 AM'],
        icon: '🏠',
      },
    ],

    upcomingOccasions: [
      {
        id: 'indigenous-occasion-1',
        name: 'Sarhul (Flower Festival)',
        date: '[Admin: Chaitra - March/April]',
        dateRange: 'Chaitra month (Spring)',
        type: 'festival',
        description: 'Santhal spring festival - Sal tree worship',
        bookingRequired: true,
        icon: '🌸',
        color: 'from-green-400 to-emerald-500',
      },
      {
        id: 'indigenous-occasion-2',
        name: 'Bhagoriya',
        date: '[Admin: Week before Holi - February/March]',
        dateRange: 'Week before Holi',
        type: 'festival',
        description: 'Bhil tribal pre-Holi festival and traditional fairs',
        bookingRequired: false,
        icon: '💃',
        color: 'from-pink-400 to-red-500',
      },
      {
        id: 'indigenous-occasion-3',
        name: 'Bastar Dussehra',
        date: '[Admin: July-October (75 days)]',
        dateRange: 'Shravan to Ashwin - 75 days',
        type: 'festival',
        description: 'World\'s longest Dussehra - unique tribal version',
        bookingRequired: true,
        icon: '🎭',
        color: 'from-orange-400 to-red-600',
      },
      {
        id: 'indigenous-occasion-4',
        name: 'Tusu Parab',
        date: '[Admin: Makar Sankranti - January]',
        dateRange: 'Mid-January',
        type: 'festival',
        description: 'Harvest festival - Tusu idol immersion',
        bookingRequired: false,
        icon: '🌾',
        color: 'from-yellow-400 to-amber-500',
      },
    ],

    culturalInsights: [
      {
        id: 'indigenous-insight-1',
        title: 'Ethical Tourism Mandatory',
        message: 'Tribal tourism must be ETHICAL. Book only through responsible tour operators who share profits with communities. Avoid voyeuristic "human zoo" tours. Respect privacy, traditions, and sacred sites.',
        type: 'requirement',
        icon: '⚖️',
        priority: 'high',
      },
      {
        id: 'indigenous-insight-2',
        title: 'Photography Permission Required',
        message: 'ALWAYS ask permission before photographing tribal people, especially during rituals. Many communities consider cameras intrusive. Some sacred ceremonies prohibit outsider photography entirely.',
        type: 'restriction',
        icon: '📷',
        priority: 'high',
      },
      {
        id: 'indigenous-insight-3',
        title: 'Seasonal Accessibility',
        message: 'Many tribal areas are remote. Monsoon (July-September) makes roads impassable. Best season: October to March. Festival dates vary by community lunar calendar. Confirm dates 1 month prior.',
        type: 'timing',
        icon: '🌧️',
        priority: 'medium',
      },
      {
        id: 'indigenous-insight-4',
        title: 'Support Local Crafts',
        message: 'Purchase tribal handicrafts (Warli paintings, Gond art, bamboo crafts) directly from artisans for fair prices. Avoid middlemen. Your support preserves dying art forms and provides livelihood.',
        type: 'tip',
        icon: '🛍️',
        priority: 'medium',
      },
    ],
  },
};
