// ========================================
// REMAINING 5 RELIGIONS DATA
// Jain, Jewish, Bahá'í, Indigenous, Parsi
// ========================================

export const remainingReligionsData = {
  // ========================================
  // 卐 JAIN PILGRIMS (PALITANA)
  // ========================================
  jain: {
    name: 'Jain Pilgrims',
    emoji: '卐',
    subtitle: 'Sacred Tirthas & Palitana Journey',
    gradient: 'from-yellow-500 to-amber-600',
    sacredText: {
      name: 'Tattvartha Sutra',
      quote: '"Parasparopagraho Jivanam" - All life is bound together by mutual support and interdependence',
      translation: 'Fundamental principle of Jainism',
      source: 'Tattvartha Sutra',
    },
    sites: [
      {
        id: 'jain-site-1',
        name: '[Admin: Palitana Temples]',
        location: '[Admin: Shatrunjaya Hill], [Admin: Gujarat]',
        subtitle: 'World\'s largest temple complex on hills',
        description: '3500 steps leading to 863 marble temples atop Shatrunjaya',
        badge: 'MOST SACRED TIRTHA',
        deity: 'Adinath (1st Tirthankara)',
        significance: '863 TEMPLES - ULTIMATE TIRTHA',
        visitors: '50,000+ during Chha Gau',
        accessibility: '3500 steps (dolis available)',
        gradient: 'from-yellow-500 to-amber-600',
      },
      {
        id: 'jain-site-2',
        name: '[Admin: Ranakpur Jain Temple]',
        location: '[Admin: Ranakpur], [Admin: Rajasthan]',
        subtitle: '1444 intricately carved pillars',
        description: 'Architectural marvel dedicated to Adinath',
        badge: 'ARCHITECTURAL WONDER',
        deity: 'Adinath',
        significance: 'MARBLE MASTERPIECE',
        visitors: '30,000+ annually',
        accessibility: 'Fully Accessible',
        gradient: 'from-white-500 to-gray-300',
      },
      {
        id: 'jain-site-3',
        name: '[Admin: Shikharji]',
        location: '[Admin: Giridih], [Admin: Jharkhand]',
        subtitle: 'Where 20 Tirthankaras attained Moksha',
        description: 'Most sacred Jain tirtha, 20 of 24 Tirthankaras achieved nirvana here',
        badge: 'HIGHEST TIRTHA',
        deity: '20 Tirthankaras',
        significance: 'MOKSHA SITE',
        visitors: '40,000+ annually',
        accessibility: 'Hill trek required',
        gradient: 'from-green-500 to-emerald-600',
      },
      {
        id: 'jain-site-4',
        name: '[Admin: Dilwara Temples]',
        location: '[Admin: Mount Abu], [Admin: Rajasthan]',
        subtitle: 'Five marble temples',
        description: 'Renowned for extraordinary marble carvings',
        badge: 'HERITAGE SITE',
        deity: 'Various Tirthankaras',
        significance: 'ARTISTIC EXCELLENCE',
        visitors: '25,000+ annually',
        accessibility: 'Accessible',
        gradient: 'from-blue-500 to-indigo-600',
      },
    ],
    rituals: [
      {
        id: 'jain-ritual-1',
        name: 'Climbing 3500 Steps (Palitana)',
        description: 'Sacred barefoot ascent up Shatrunjaya Hill',
        duration: '3-4 hours (ascent)',
        site: '[Admin: Palitana]',
        procedure: 'Barefoot climb starting before dawn, no food/water carried up',
        significance: 'Penance and purification',
        participants: 'All able pilgrims',
        icon: '⛰️',
      },
      {
        id: 'jain-ritual-2',
        name: 'Parikrama (Circumambulation)',
        description: 'Walking around sacred temples',
        duration: '30 minutes - 2 hours',
        site: '[Admin: All Tirthas]',
        procedure: 'Clockwise walking meditation around main temple',
        significance: 'Respect and devotion',
        participants: 'All devotees',
        icon: '🚶',
      },
      {
        id: 'jain-ritual-3',
        name: 'Navkar Mantra Recitation',
        description: 'Chanting the most fundamental Jain prayer',
        duration: '5-15 minutes',
        site: '[Admin: Anywhere]',
        procedure: 'Recitation of "Namo Arihantanam" mantra',
        significance: 'Salutation to enlightened beings',
        participants: 'All Jains',
        icon: '📿',
      },
      {
        id: 'jain-ritual-4',
        name: 'Pratikramana',
        description: 'Ritual of repentance and confession',
        duration: '45 minutes',
        site: '[Admin: Temples & Homes]',
        procedure: 'Seeking forgiveness for sins committed',
        significance: 'Spiritual cleansing',
        participants: 'Jain devotees',
        icon: '🙏',
      },
      {
        id: 'jain-ritual-5',
        name: 'Abhishek (Bathing Ritual)',
        description: 'Ceremonial bathing of Tirthankara statues',
        duration: '20-30 minutes',
        site: '[Admin: Jain Temples]',
        procedure: 'Bathing idol with milk, saffron, sandalwood',
        significance: 'Purification and devotion',
        participants: 'Priests and devotees',
        icon: '💧',
      },
    ],
    festivals: [
      {
        id: 'jain-festival-1',
        name: 'Chha Gau Teerth Yatra',
        date: '[Admin: Kartika Purnima - November]',
        dateRange: 'Kartik Purnima (Oct-Nov)',
        description: 'Largest Jain pilgrimage to Palitana',
        significance: 'MOST SACRED PILGRIMAGE DAY',
        celebrations: 'Mass ascent of Shatrunjaya, temple rituals, processions',
        venue: '[Admin: Palitana]',
        expectedVisitors: '100,000+ over 3 days',
        rituals: ['3500 steps climb', 'Temple darshan', 'Aarti'],
        icon: '⛰️',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'jain-festival-2',
        name: 'Mahavir Jayanti',
        date: '[Admin: Chaitra Sud 13 - March/April]',
        dateRange: 'Chaitra month (Mar-Apr)',
        description: 'Birth anniversary of Lord Mahavir (24th Tirthankara)',
        significance: 'BIRTH OF LAST TIRTHANKARA',
        celebrations: 'Processions, abhishek, lectures on Jain principles',
        venue: '[Admin: All Jain Temples]',
        expectedVisitors: 'Millions nationwide',
        rituals: ['Abhishek ceremony', 'Rath Yatra', 'Charitable acts'],
        icon: '👶',
        color: 'from-orange-400 to-red-500',
      },
      {
        id: 'jain-festival-3',
        name: 'Paryushana Parva',
        date: '[Admin: Bhadrapada - August/September]',
        dateRange: 'Bhadrapada (Aug-Sep) - 8 days',
        description: 'Most important annual Jain festival of forgiveness',
        significance: 'SPIRITUAL CLEANSING',
        celebrations: 'Fasting, meditation, scripture study, forgiveness',
        venue: '[Admin: All Jain Communities]',
        expectedVisitors: 'Community-wide',
        rituals: ['Pratikramana', 'Samvatsari (forgiveness)', 'Fasting'],
        icon: '🕉️',
        color: 'from-green-400 to-emerald-500',
      },
      {
        id: 'jain-festival-4',
        name: 'Diwali (Mahavir Nirvana)',
        date: '[Admin: Kartik Amavasya - October/November]',
        dateRange: 'Kartik Amavasya',
        description: 'Commemoration of Mahavir\'s attainment of Moksha',
        significance: 'NIRVANA OF MAHAVIR',
        celebrations: 'Oil lamps, prayers, reading of Uttaradhyayan Sutra',
        venue: '[Admin: All Jain Temples]',
        expectedVisitors: 'Community celebration',
        rituals: ['Lamp lighting', 'Scripture reading', 'New year rituals'],
        icon: '🪔',
        color: 'from-amber-400 to-yellow-500',
      },
    ],
    packages: [
      {
        id: 'jain-package-1',
        name: '[Admin: Palitana Sacred Climb]',
        duration: '5 days',
        price: '₹45,000',
        description: 'Complete Palitana pilgrimage with preparation and support',
        inclusions: [
          'Pre-climb health assessment',
          'Doli (palanquin) arrangement if needed',
          'Pure vegetarian Jain meals',
          'Temple entry arrangements',
          'Senior care support',
          'Medical support available',
          'Accommodation near base',
        ],
        highlights: [
          '3500 steps sacred climb',
          '863 marble temples darshan',
          'Sunrise from summit',
          'Guided temple tour',
        ],
        dates: '[Admin: Oct-Mar (cool season)]',
        groupSize: '6-12 people',
        badge: 'PALITANA SPECIAL',
        gradient: 'from-yellow-500 to-amber-600',
      },
      {
        id: 'jain-package-2',
        name: '[Admin: Rajasthan Jain Circuit]',
        duration: '8 days',
        price: '₹65,000',
        description: 'Tour of architectural marvels - Ranakpur and Dilwara',
        inclusions: [
          'AC transport',
          'Strict Jain vegetarian food',
          'Temple accommodation',
          'Photography permits',
          'Expert guides',
          'Cultural insights',
        ],
        highlights: [
          'Ranakpur 1444 pillars',
          'Dilwara marble carvings',
          'Architecture study',
          'Jain heritage exploration',
        ],
        dates: '[Admin: Sep-Mar]',
        groupSize: '8-15 people',
        badge: 'HERITAGE TOUR',
        gradient: 'from-blue-500 to-purple-600',
      },
      {
        id: 'jain-package-3',
        name: '[Admin: Chha Gau Festival Package]',
        duration: '4 days',
        price: '₹50,000',
        description: 'Experience the grand Kartik Purnima pilgrimage',
        inclusions: [
          'Festival access',
          'Priority doli service',
          'Jain sattvic meals',
          'Temple ceremony participation',
          'Health monitoring',
          'Group support',
        ],
        highlights: [
          '100,000+ pilgrims gathering',
          'Special ceremonies',
          'Community darshan',
          'Sacred atmosphere',
        ],
        dates: '[Admin: Kartik Purnima]',
        groupSize: '10-15 people',
        badge: 'FESTIVAL SPECIAL',
        gradient: 'from-orange-500 to-red-600',
      },
    ],
  },

  // ========================================
  // ✡ JEWISH HERITAGE
  // ========================================
  jewish: {
    name: 'Jewish Heritage',
    emoji: '✡',
    subtitle: 'Ancient Synagogues & Sacred History',
    gradient: 'from-blue-500 to-indigo-600',
    sacredText: {
      name: 'Torah',
      quote: '"Hear, O Israel: The LORD our God, the LORD is one..."',
      translation: 'Shema Yisrael - Deuteronomy 6:4',
      source: 'Torah - Five Books of Moses',
    },
    sites: [
      {
        id: 'jewish-site-1',
        name: '[Admin: Paradesi Synagogue]',
        location: '[Admin: Kochi], [Admin: Kerala]',
        subtitle: 'Oldest active synagogue in Commonwealth',
        description: 'Built in 1568, features hand-painted Chinese tiles',
        badge: 'OLDEST SYNAGOGUE',
        deity: 'Torah Ark',
        significance: 'COCHIN JEWISH LEGACY',
        visitors: '10,000+ annually',
        accessibility: 'Fully Accessible',
        gradient: 'from-blue-500 to-cyan-600',
      },
      {
        id: 'jewish-site-2',
        name: '[Admin: Keneseth Eliyahoo Synagogue]',
        location: '[Admin: Mumbai], [Admin: Maharashtra]',
        subtitle: 'Bene Israeli synagogue',
        description: '140-year-old synagogue serving Bene Israel community',
        badge: 'HERITAGE SYNAGOGUE',
        deity: 'Torah Scroll',
        significance: 'BENE ISRAEL CENTER',
        visitors: '5,000+ annually',
        accessibility: 'Accessible',
        gradient: 'from-indigo-500 to-purple-600',
      },
      {
        id: 'jewish-site-3',
        name: '[Admin: Magen David Synagogue]',
        location: '[Admin: Kolkata], [Admin: West Bengal]',
        subtitle: 'Baghdadi Jewish heritage',
        description: 'Built in 1884 by Baghdadi Jews, ornate architecture',
        badge: 'BAGHDADI HERITAGE',
        deity: 'Torah',
        significance: 'BAGHDADI JEWISH COMMUNITY',
        visitors: '3,000+ annually',
        accessibility: 'Accessible',
        gradient: 'from-amber-500 to-orange-600',
      },
      {
        id: 'jewish-site-4',
        name: '[Admin: Jewish Cemetery Kochi]',
        location: '[Admin: Kochi], [Admin: Kerala]',
        subtitle: 'Ancient Jewish burial ground',
        description: 'Historic cemetery dating back centuries',
        badge: 'ANCIENT SITE',
        deity: 'Memorial Site',
        significance: 'JEWISH ANCESTRY',
        visitors: 'Heritage visitors',
        accessibility: 'Limited',
        gradient: 'from-gray-400 to-gray-600',
      },
    ],
    rituals: [
      {
        id: 'jewish-ritual-1',
        name: 'Sabbath Observance',
        description: 'Friday evening to Saturday evening holy day',
        duration: '25 hours',
        site: '[Admin: Synagogues & Homes]',
        procedure: 'Candle lighting, Kiddush, meals, Torah reading, Havdalah',
        significance: 'Weekly day of rest and worship',
        participants: 'Jewish families',
        icon: '🕎',
      },
      {
        id: 'jewish-ritual-2',
        name: 'Torah Reading',
        description: 'Public reading of Torah scrolls',
        duration: '30-45 minutes',
        site: '[Admin: Synagogues]',
        procedure: 'Cantillation of Torah portions during services',
        significance: 'Transmission of sacred text',
        participants: 'Congregation',
        icon: '📜',
      },
      {
        id: 'jewish-ritual-3',
        name: 'Bar/Bat Mitzvah',
        description: 'Coming of age ceremony',
        duration: '1-2 hours',
        site: '[Admin: Synagogues]',
        procedure: 'First Torah reading as adult, celebration',
        significance: 'Religious maturity',
        participants: '13-year-olds',
        icon: '🎉',
      },
      {
        id: 'jewish-ritual-4',
        name: 'Tefillin (Phylacteries)',
        description: 'Daily prayer with leather boxes',
        duration: '10-20 minutes',
        site: '[Admin: Synagogue/Home]',
        procedure: 'Wrapping leather straps with Torah verses',
        significance: 'Daily commandment',
        participants: 'Adult Jewish men',
        icon: '📿',
      },
    ],
    festivals: [
      {
        id: 'jewish-festival-1',
        name: 'Pesach (Passover)',
        date: '[Admin: 15 Nisan - March/April]',
        dateRange: 'Nisan 15 (Spring)',
        description: 'Commemoration of Exodus from Egypt',
        significance: 'FREEDOM FROM SLAVERY',
        celebrations: 'Seder meal, matzah, retelling Exodus story',
        venue: '[Admin: Homes & Synagogues]',
        expectedVisitors: 'Community-wide',
        rituals: ['Seder ceremony', 'Four cups of wine', 'Matzah eating'],
        icon: '🍷',
        color: 'from-blue-400 to-indigo-500',
      },
      {
        id: 'jewish-festival-2',
        name: 'Rosh Hashanah',
        date: '[Admin: 1 Tishrei - September/October]',
        dateRange: 'Tishrei 1-2 (Fall)',
        description: 'Jewish New Year',
        significance: 'NEW YEAR & JUDGEMENT',
        celebrations: 'Shofar blowing, apples with honey, prayers',
        venue: '[Admin: Synagogues]',
        expectedVisitors: 'Full community',
        rituals: ['Shofar blast', 'Tashlich', 'Special meals'],
        icon: '📯',
        color: 'from-amber-400 to-yellow-500',
      },
      {
        id: 'jewish-festival-3',
        name: 'Yom Kippur',
        date: '[Admin: 10 Tishrei - September/October]',
        dateRange: 'Tishrei 10',
        description: 'Day of Atonement - holiest day',
        significance: 'DAY OF ATONEMENT',
        celebrations: '25-hour fast, prayer, repentance',
        venue: '[Admin: Synagogues]',
        expectedVisitors: 'Highest attendance',
        rituals: ['Kol Nidre', 'Fasting', 'Neilah service'],
        icon: '🙏',
        color: 'from-purple-500 to-indigo-600',
      },
      {
        id: 'jewish-festival-4',
        name: 'Hanukkah',
        date: '[Admin: 25 Kislev - November/December]',
        dateRange: 'Kislev 25 - 8 days',
        description: 'Festival of Lights commemorating Temple rededication',
        significance: 'MIRACLE OF OIL',
        celebrations: 'Menorah lighting, dreidel games, oil foods',
        venue: '[Admin: Homes & Synagogues]',
        expectedVisitors: 'Families',
        rituals: ['Menorah lighting', 'Blessings', 'Songs'],
        icon: '🕎',
        color: 'from-blue-400 to-cyan-500',
      },
      {
        id: 'jewish-festival-5',
        name: 'Purim',
        date: '[Admin: 14 Adar - February/March]',
        dateRange: 'Adar 14',
        description: 'Celebration of deliverance from Haman',
        significance: 'SALVATION STORY',
        celebrations: 'Megillah reading, costumes, gifts, feast',
        venue: '[Admin: Synagogues]',
        expectedVisitors: 'Community celebration',
        rituals: ['Megillah reading', 'Mishloach manot', 'Seudah'],
        icon: '🎭',
        color: 'from-pink-400 to-rose-500',
      },
    ],
    packages: [
      {
        id: 'jewish-package-1',
        name: '[Admin: Jewish Heritage Tour]',
        duration: '7 days',
        price: '₹60,000',
        description: 'Explore ancient Jewish communities in India',
        inclusions: [
          'AC transport',
          'Kosher meals arranged',
          'Synagogue visits',
          'Heritage guides',
          'Comfortable accommodation',
          'Cultural documentation',
        ],
        highlights: [
          'Paradesi Synagogue Kochi',
          'Bene Israel Mumbai',
          'Baghdadi community Kolkata',
          'Jewish cemetery tours',
        ],
        dates: '[Admin: Year-round (avoid Sabbath travel)]',
        groupSize: '6-10 people',
        badge: 'HERITAGE TOUR',
        gradient: 'from-blue-500 to-indigo-600',
      },
      {
        id: 'jewish-package-2',
        name: '[Admin: Sabbath Experience Package]',
        duration: '3 days',
        price: '₹35,000',
        description: 'Experience traditional Sabbath with community',
        inclusions: [
          'Sabbath meals',
          'Synagogue services',
          'Community hosting',
          'Kosher accommodation',
          'Prayer books provided',
        ],
        highlights: [
          'Friday evening Kabbalat Shabbat',
          'Saturday morning service',
          'Torah reading participation',
          'Havdalah ceremony',
        ],
        dates: '[Admin: Any Friday-Saturday]',
        groupSize: '4-8 people',
        badge: 'SABBATH EXPERIENCE',
        gradient: 'from-purple-500 to-pink-600',
      },
      {
        id: 'jewish-package-3',
        name: '[Admin: Pesach in India]',
        duration: '8 days',
        price: '₹75,000',
        description: 'Celebrate Passover with Indian Jewish community',
        inclusions: [
          'Passover Seder meals',
          'Kosher for Passover food',
          'Haggadah provided',
          'Synagogue services',
          'Community integration',
        ],
        highlights: [
          'Traditional Seder',
          'Matzah-only meals',
          'Community celebrations',
          'Exodus storytelling',
        ],
        dates: '[Admin: 15-22 Nisan]',
        groupSize: '8-12 people',
        badge: 'FESTIVAL SPECIAL',
        gradient: 'from-blue-400 to-teal-500',
      },
    ],
  },

  // ========================================
  // ★ BAHÁ'Í VISITORS
  // ========================================
  bahai: {
    name: 'Bahá\'í Visitors',
    emoji: '★',
    subtitle: 'Lotus Temple & Universal Unity',
    gradient: 'from-pink-500 to-rose-600',
    sacredText: {
      name: 'Kitáb-i-Aqdas',
      quote: '"The earth is but one country, and mankind its citizens..."',
      translation: 'Bahá\'u\'lláh - Principle of Unity',
      source: 'Kitáb-i-Aqdas (Most Holy Book)',
    },
    sites: [
      {
        id: 'bahai-site-1',
        name: '[Admin: Lotus Temple]',
        location: '[Admin: New Delhi], [Admin: Delhi]',
        subtitle: 'Bahá\'í House of Worship',
        description: 'Iconic lotus-shaped temple, one of the most visited buildings in the world',
        badge: 'MOST VISITED',
        deity: 'Universal Worship',
        significance: 'HOUSE OF WORSHIP',
        visitors: '4 million+ annually',
        accessibility: 'Fully Accessible',
        gradient: 'from-pink-500 to-rose-600',
      },
      {
        id: 'bahai-site-2',
        name: '[Admin: Bahá\'í Center Bihar]',
        location: '[Admin: Bihar Sharif], [Admin: Bihar]',
        subtitle: 'Historic Bahá\'í community center',
        description: 'Community gathering place for Bahá\'í teachings',
        badge: 'COMMUNITY HUB',
        deity: 'Unity Teachings',
        significance: 'EDUCATIONAL CENTER',
        visitors: '5,000+ annually',
        accessibility: 'Accessible',
        gradient: 'from-blue-500 to-indigo-600',
      },
    ],
    rituals: [
      {
        id: 'bahai-ritual-1',
        name: 'Prayer and Meditation',
        description: 'Individual and collective prayers from Bahá\'í writings',
        duration: '15-30 minutes',
        site: '[Admin: Lotus Temple & Homes]',
        procedure: 'Recitation of prayers revealed by Bahá\'u\'lláh',
        significance: 'Spiritual nourishment',
        participants: 'All visitors',
        icon: '🙏',
      },
      {
        id: 'bahai-ritual-2',
        name: 'Devotional Gatherings',
        description: 'Community prayers and music',
        duration: '1 hour',
        site: '[Admin: Bahá\'í Centers]',
        procedure: 'Reading sacred texts, prayers, music',
        significance: 'Unity and worship',
        participants: 'Open to all',
        icon: '🎵',
      },
      {
        id: 'bahai-ritual-3',
        name: 'Nineteen Day Feast',
        description: 'Monthly Bahá\'í community gathering',
        duration: '2-3 hours',
        site: '[Admin: Bahá\'í Homes]',
        procedure: 'Devotional, consultative, and social portions',
        significance: 'Community unity',
        participants: 'Bahá\'í community',
        icon: '🍽️',
      },
    ],
    festivals: [
      {
        id: 'bahai-festival-1',
        name: 'Naw-Rúz (Bahá\'í New Year)',
        date: '[Admin: March 21]',
        dateRange: 'March 21 (Spring Equinox)',
        description: 'Bahá\'í New Year celebration',
        significance: 'NEW YEAR',
        celebrations: 'Feasts, prayers, music, cultural programs',
        venue: '[Admin: Bahá\'í Centers & Homes]',
        expectedVisitors: 'Community-wide',
        rituals: ['Prayers', 'Music', 'Feast'],
        icon: '🌸',
        color: 'from-pink-400 to-rose-500',
      },
      {
        id: 'bahai-festival-2',
        name: 'Ridván',
        date: '[Admin: April 21 - May 2]',
        dateRange: '12 days in April-May',
        description: 'Declaration of Bahá\'u\'lláh - most holy festival',
        significance: 'MOST SACRED PERIOD',
        celebrations: 'Prayers, readings, community gatherings',
        venue: '[Admin: Bahá\'í Communities]',
        expectedVisitors: 'All Bahá\'ís',
        rituals: ['Special prayers', 'Readings', 'Unity programs'],
        icon: '🌟',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'bahai-festival-3',
        name: 'Birth of Bahá\'u\'lláh',
        date: '[Admin: November 12]',
        dateRange: 'November 12',
        description: 'Birthday of Bahá\'u\'lláh, founder of Bahá\'í Faith',
        significance: 'FOUNDER\'S BIRTH',
        celebrations: 'Devotional programs, readings, music',
        venue: '[Admin: Lotus Temple & Centers]',
        expectedVisitors: 'Thousands',
        rituals: ['Prayers', 'Readings', 'Music'],
        icon: '🎂',
        color: 'from-blue-400 to-purple-500',
      },
    ],
    packages: [
      {
        id: 'bahai-package-1',
        name: '[Admin: Lotus Temple Experience]',
        duration: '3 days',
        price: '₹30,000',
        description: 'Explore Bahá\'í teachings at the iconic Lotus Temple',
        inclusions: [
          'Lotus Temple guided tour',
          'Devotional programs',
          'Unity teachings session',
          'Comfortable accommodation',
          'Meals included',
          'Transport',
        ],
        highlights: [
          'Lotus Temple meditation',
          'Bahá\'í teachings introduction',
          'Unity in diversity programs',
          'Silent prayer time',
        ],
        dates: '[Admin: Year-round]',
        groupSize: '10-20 people',
        badge: 'SPIRITUAL EXPERIENCE',
        gradient: 'from-pink-500 to-rose-600',
      },
      {
        id: 'bahai-package-2',
        name: '[Admin: Naw-Rúz Celebration]',
        duration: '2 days',
        price: '₹25,000',
        description: 'Join Bahá\'í New Year festivities',
        inclusions: [
          'Naw-Rúz feast',
          'Cultural programs',
          'Community integration',
          'Devotional music',
          'Accommodation',
        ],
        highlights: [
          'New Year prayers',
          'Multicultural celebration',
          'Unity feast',
          'Music and arts',
        ],
        dates: '[Admin: March 21]',
        groupSize: '15-25 people',
        badge: 'FESTIVAL SPECIAL',
        gradient: 'from-green-400 to-teal-500',
      },
    ],
  },

  // ========================================
  // 🌿 INDIGENOUS & TRIBAL
  // ========================================
  indigenous: {
    name: 'Indigenous & Tribal',
    emoji: '🌿',
    subtitle: 'Ancient Traditions & Sacred Festivals',
    gradient: 'from-green-600 to-emerald-700',
    sacredText: {
      name: 'Oral Traditions',
      quote: '"The forest is our temple, the river our priest, and nature our sacred text..."',
      translation: 'Tribal wisdom passed through generations',
      source: 'Oral traditions of indigenous communities',
    },
    sites: [
      {
        id: 'indigenous-site-1',
        name: '[Admin: Bhil Sacred Groves]',
        location: '[Admin: Rajasthan/Madhya Pradesh]',
        subtitle: 'Sacred forest worship sites',
        description: 'Ancient groves protected by Bhil tribes for generations',
        badge: 'SACRED GROVES',
        deity: 'Nature Spirits',
        significance: 'ENVIRONMENTAL SPIRITUALITY',
        visitors: 'Tribal community + researchers',
        accessibility: 'Guided access only',
        gradient: 'from-green-600 to-emerald-700',
      },
      {
        id: 'indigenous-site-2',
        name: '[Admin: Sarhul Celebration Ground]',
        location: '[Admin: Jharkhand]',
        subtitle: 'Santhal worship of Sal trees',
        description: 'Sacred site where Santhal tribes worship during Sarhul',
        badge: 'FESTIVAL GROUND',
        deity: 'Sal Tree Deity',
        significance: 'SPRING WORSHIP',
        visitors: '50,000+ during Sarhul',
        accessibility: 'Open during festivals',
        gradient: 'from-amber-500 to-orange-600',
      },
      {
        id: 'indigenous-site-3',
        name: '[Admin: Bastar Dussehra Ground]',
        location: '[Admin: Bastar], [Admin: Chhattisgarh]',
        subtitle: '75-day tribal Dussehra celebration',
        description: 'Unique tribal interpretation of Dussehra',
        badge: 'LONGEST FESTIVAL',
        deity: 'Danteshwari Devi',
        significance: '75-DAY CELEBRATION',
        visitors: '100,000+ over festival',
        accessibility: 'Open to visitors',
        gradient: 'from-red-500 to-pink-600',
      },
    ],
    rituals: [
      {
        id: 'indigenous-ritual-1',
        name: 'Body Piercing (Mansa Puja)',
        description: 'Ritual body piercing for deity appeasement',
        duration: 'Festival day',
        site: '[Admin: Manasa Worship Sites]',
        procedure: 'Devotees pierce tongue, cheeks with needles',
        significance: 'Demonstrating devotion',
        participants: 'Voluntary devotees',
        icon: '🔱',
      },
      {
        id: 'indigenous-ritual-2',
        name: 'Sarhul Flower Offering',
        description: 'Offering Sal tree flowers',
        duration: 'Day-long ceremony',
        site: '[Admin: Sacred Sal Groves]',
        procedure: 'Priests offer flowers, pray for good harvest',
        significance: 'Spring welcome, fertility',
        participants: 'Santhal community',
        icon: '🌸',
      },
      {
        id: 'indigenous-ritual-3',
        name: 'Tusu Parab Immersion',
        description: 'Immersion of Tusu idol in river',
        duration: '2-3 hours',
        site: '[Admin: Rivers in Jharkhand]',
        procedure: 'Procession with Tusu idol, songs, immersion',
        significance: 'Harvest thanksgiving',
        participants: 'Village communities',
        icon: '🌊',
      },
    ],
    festivals: [
      {
        id: 'indigenous-festival-1',
        name: 'Sarhul (Flower Festival)',
        date: '[Admin: Chaitra - March/April]',
        dateRange: 'Chaitra month (Spring)',
        description: 'Santhal spring festival worshipping Sal trees',
        significance: 'SPRING CELEBRATION',
        celebrations: 'Flower offerings, traditional dance, music',
        venue: '[Admin: Jharkhand villages]',
        expectedVisitors: '50,000+ tribal community',
        rituals: ['Sal tree worship', 'Traditional dance', 'Flower offerings'],
        icon: '🌸',
        color: 'from-green-400 to-emerald-500',
      },
      {
        id: 'indigenous-festival-2',
        name: 'Bhagoriya',
        date: '[Admin: Week before Holi - February/March]',
        dateRange: 'Week before Holi',
        description: 'Bhil tribal pre-Holi festival and marriage market',
        significance: 'TRIBAL COURTSHIP',
        celebrations: 'Traditional dances, elopements, markets',
        venue: '[Admin: Madhya Pradesh/Rajasthan]',
        expectedVisitors: '30,000+ tribal youth',
        rituals: ['Tribal dance', 'Courtship rituals', 'Markets'],
        icon: '💃',
        color: 'from-pink-400 to-red-500',
      },
      {
        id: 'indigenous-festival-3',
        name: 'Bastar Dussehra',
        date: '[Admin: July-October (75 days)]',
        dateRange: 'Shravan to Ashwin (75 days)',
        description: 'World\'s longest Dussehra celebration',
        significance: 'LONGEST FESTIVAL',
        celebrations: 'Tribal rituals, processions, unique traditions',
        venue: '[Admin: Bastar, Chhattisgarh]',
        expectedVisitors: '100,000+ over duration',
        rituals: ['Pata Jatra', 'Rath Yatra', 'Traditional ceremonies'],
        icon: '🎭',
        color: 'from-orange-400 to-red-600',
      },
      {
        id: 'indigenous-festival-4',
        name: 'Tusu Parab',
        date: '[Admin: Makar Sankranti - January]',
        dateRange: 'Mid-January',
        description: 'Harvest festival of tribal communities',
        significance: 'HARVEST THANKSGIVING',
        celebrations: 'Tusu idol worship, songs, immersion',
        venue: '[Admin: Jharkhand/West Bengal]',
        expectedVisitors: 'Village communities',
        rituals: ['Tusu songs', 'Idol immersion', 'Harvest celebration'],
        icon: '🌾',
        color: 'from-yellow-400 to-amber-500',
      },
    ],
    packages: [
      {
        id: 'indigenous-package-1',
        name: '[Admin: Tribal Heritage Immersion]',
        duration: '7 days',
        price: '₹55,000',
        description: 'Experience authentic tribal culture and traditions',
        inclusions: [
          'Village homestays',
          'Tribal guide',
          'Traditional meals',
          'Cultural performances',
          'Craft workshops',
          'Ethical tourism approach',
        ],
        highlights: [
          'Live with tribal families',
          'Traditional dance learning',
          'Craft workshops',
          'Sacred grove visits',
        ],
        dates: '[Admin: Oct-Mar]',
        groupSize: '4-8 people',
        badge: 'IMMERSIVE EXPERIENCE',
        gradient: 'from-green-600 to-emerald-700',
      },
      {
        id: 'indigenous-package-2',
        name: '[Admin: Sarhul Festival Experience]',
        duration: '4 days',
        price: '₹40,000',
        description: 'Witness Santhal spring festival',
        inclusions: [
          'Festival access',
          'Traditional accommodation',
          'Tribal meals',
          'Cultural guide',
          'Dance participation',
        ],
        highlights: [
          'Sal tree worship',
          'Traditional Santhal dance',
          'Spring rituals',
          'Community feast',
        ],
        dates: '[Admin: Chaitra - March/April]',
        groupSize: '6-10 people',
        badge: 'FESTIVAL SPECIAL',
        gradient: 'from-orange-400 to-amber-500',
      },
    ],
  },

  // ========================================
  // 🔥 PARSI HERITAGE
  // ========================================
  parsi: {
    name: 'Parsi Heritage',
    emoji: '🔥',
    subtitle: 'Fire Temples & Nowruz Celebrations',
    gradient: 'from-orange-600 to-red-700',
    sacredText: {
      name: 'Avesta',
      quote: '"Good Thoughts, Good Words, Good Deeds (Humata, Hukhta, Hvarshta)"',
      translation: 'Foundational Zoroastrian principle',
      source: 'Avesta - Yasna',
    },
    sites: [
      {
        id: 'parsi-site-1',
        name: '[Admin: Udvada Atash Behram]',
        location: '[Admin: Udvada], [Admin: Gujarat]',
        subtitle: 'Oldest fire temple in India',
        description: 'Sacred fire burning continuously for over 1000 years',
        badge: 'MOST SACRED',
        deity: 'Sacred Fire (Atash)',
        significance: '1000+ YEAR FIRE',
        visitors: '50,000+ Parsi pilgrims annually',
        accessibility: 'Parsis only (inner sanctum)',
        gradient: 'from-orange-600 to-red-700',
      },
      {
        id: 'parsi-site-2',
        name: '[Admin: Towers of Silence Mumbai]',
        location: '[Admin: Mumbai], [Admin: Maharashtra]',
        subtitle: 'Dakhma - Traditional burial site',
        description: 'Traditional Zoroastrian funeral structures',
        badge: 'SACRED SITE',
        deity: 'Sky Burial',
        significance: 'TRADITIONAL FUNERARY',
        visitors: 'Restricted access',
        accessibility: 'Community access only',
        gradient: 'from-gray-600 to-gray-800',
      },
      {
        id: 'parsi-site-3',
        name: '[Admin: Iranshah Atash Behram]',
        location: '[Admin: Udvada], [Admin: Gujarat]',
        subtitle: 'King of Fires',
        description: 'Highest grade of sacred fire in India',
        badge: 'ATASH BEHRAM',
        deity: 'Iranshah (Sacred Fire)',
        significance: 'HIGHEST GRADE FIRE',
        visitors: 'Parsi community',
        accessibility: 'Parsis only',
        gradient: 'from-yellow-500 to-orange-600',
      },
    ],
    rituals: [
      {
        id: 'parsi-ritual-1',
        name: 'Fire Worship',
        description: 'Daily prayers before sacred fire',
        duration: '15-30 minutes',
        site: '[Admin: Fire Temples]',
        procedure: 'Prayers while facing sacred fire, offerings of sandalwood',
        significance: 'Symbol of divine light and purity',
        participants: 'Parsi community',
        icon: '🔥',
      },
      {
        id: 'parsi-ritual-2',
        name: 'Kusti Ceremony',
        description: 'Daily ritual of tying sacred thread',
        duration: '5-10 minutes',
        site: '[Admin: Home/Temple]',
        procedure: 'Untying and retying sacred cord while reciting prayers',
        significance: 'Renewal of covenant',
        participants: 'All Zoroastrians',
        icon: '🔗',
      },
      {
        id: 'parsi-ritual-3',
        name: 'Navjote',
        description: 'Initiation ceremony for children',
        duration: '2-3 hours',
        site: '[Admin: Fire Temples/Homes]',
        procedure: 'Child receives sudreh (sacred shirt) and kusti (cord)',
        significance: 'Entry into faith',
        participants: '7-9 year olds',
        icon: '👶',
      },
    ],
    festivals: [
      {
        id: 'parsi-festival-1',
        name: 'Nowruz (Parsi New Year)',
        date: '[Admin: March 21 (Spring Equinox)]',
        dateRange: 'March 21',
        description: 'Zoroastrian/Parsi New Year celebration',
        significance: 'NEW YEAR',
        celebrations: 'Fire temple visits, feasts, new clothes, charity',
        venue: '[Admin: Fire Temples & Homes]',
        expectedVisitors: 'Entire Parsi community',
        rituals: ['Fire temple prayers', 'Haft-Seen table', 'Family feast'],
        icon: '🎊',
        color: 'from-orange-400 to-red-500',
      },
      {
        id: 'parsi-festival-2',
        name: 'Khordad Sal',
        date: '[Admin: August]',
        dateRange: 'Khordad Mah, Khordad Roz',
        description: 'Birth anniversary of Prophet Zarathushtra',
        significance: 'PROPHET\'S BIRTHDAY',
        celebrations: 'Fire temple ceremonies, prayers, community meals',
        venue: '[Admin: All Fire Temples]',
        expectedVisitors: 'Parsi community nationwide',
        rituals: ['Special prayers', 'Jashan ceremony', 'Charity'],
        icon: '🌟',
        color: 'from-yellow-400 to-amber-500',
      },
      {
        id: 'parsi-festival-3',
        name: 'Pateti',
        date: '[Admin: Day before Nowruz]',
        dateRange: 'March 20',
        description: 'Day of repentance before New Year',
        significance: 'REPENTANCE DAY',
        celebrations: 'Prayers, confession, preparation for new year',
        venue: '[Admin: Fire Temples]',
        expectedVisitors: 'Parsi community',
        rituals: ['Confession prayers', 'Fire temple visit', 'Charity'],
        icon: '🙏',
        color: 'from-purple-400 to-indigo-500',
      },
    ],
    packages: [
      {
        id: 'parsi-package-1',
        name: '[Admin: Parsi Heritage Tour]',
        duration: '5 days',
        price: '₹50,000',
        description: 'Explore Parsi history and fire temples (external)',
        inclusions: [
          'Fire temple exterior tours',
          'Parsi cuisine experience',
          'Heritage site visits',
          'Cultural guide',
          'Comfortable accommodation',
        ],
        highlights: [
          'Udvada Atash Behram (exterior)',
          'Parsi Colony Mumbai',
          'Traditional Parsi meals',
          'Heritage architecture',
        ],
        dates: '[Admin: Year-round]',
        groupSize: '6-10 people',
        badge: 'HERITAGE TOUR',
        gradient: 'from-orange-600 to-red-700',
      },
      {
        id: 'parsi-package-2',
        name: '[Admin: Nowruz Celebration]',
        duration: '3 days',
        price: '₹40,000',
        description: 'Experience Parsi New Year festivities',
        inclusions: [
          'Nowruz feast',
          'Cultural programs',
          'Parsi cuisine',
          'Heritage tours',
          'Accommodation',
        ],
        highlights: [
          'Nowruz celebrations',
          'Traditional Parsi feast',
          'Fire temple visits (exterior)',
          'Community interaction',
        ],
        dates: '[Admin: March 21]',
        groupSize: '8-12 people',
        badge: 'FESTIVAL SPECIAL',
        gradient: 'from-yellow-500 to-orange-600',
      },
    ],
  },
};
